### ISSUE TITLE
Error when trying to import key

### ISSUE THREAD

**Issue by AlexHockaday** [tmiland/TeamSpeak3-Client#2]
When trying to download the key I get the following error:

$ sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys A9EA5FFA30697D15
Executing: /tmp/apt-key-gpghome.xNRqBgZY7J/gpg.1.sh --keyserver hkps://keys.openpgp.org --recv-keys A9EA5FFA30697D15
gpg: key A9EA5FFA30697D15: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1

When trying to get the same key from a different keyserver (keyserver.ubuntu.com):

$ sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv-keys A9EA5FFA30697D15
Executing: /tmp/apt-key-gpghome.Z7uDeiDDw9/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com --recv-keys A9EA5FFA30697D15
gpg: keyserver receive failed: No data

According to this [superuser question](https://superuser.com/questions/1485213/gpg-cant-import-key-new-key-but-contains-no-user-id-skipped), 

> the keys.openpgp.org keyserver, which has an owner approval system – it will strip all user IDs unless the owner of the corresponding email address has allowed them to be published.

**Comment by tmiland** [comment]
Thanks for reporting. 

I have removed the repo, use the manual install instead.
